name: lint-test-deploy

on: [push]

jobs:
  test:
    name: Lint / Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '12', '14', '16' ]
        cypress: [ '5.6.0', '6.9.1', '7.7.0', '8.5.0' ]
        wp: [ '5.7', '5.8' ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: CYPRESS_INSTALL_BINARY=${{ matrix.cypress }} npm ci
      - name: Lint
        run: npm run lint
      - name: "Configure environment with WP ${{ matrix.wp }}"
        run: |
          echo -e '{\n\t"core": "WordPress/WordPress#${{ matrix.wp }}"\n}' > ./.wp-env.override.json
      - name: Start WordPress environment
        run: |
          chmod -R 767 ./ # TODO: Possibly integrate in wp-env
          npm run wp-env start
      - name: Run E2E tests
        run: npm run test:e2e -- --config '{"env":{"cypress-wp-test-utils":{"wpVersion":${{ matrix.wp }}}}}'

  deploy-dry-run:
    name: '[DRY RUN] Publish package'

    # only run on master but not tags
    if: ${{ github.ref == 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/') }}

    needs: [ test ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - name: '[DRY RUN] Publish package to npm registry'
        run: npm publish --dry-run

  deploy:
    name: Publish package

    # only run on tags
    if: startsWith(github.ref, 'refs/tags/')

    needs: [ test ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package to npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
